learning_rate: 0.0001
model_config:
  aggregator_name: TrnasoformerAggregator
  aggregator_params:
    nhead: 4
    num_layers: 4
    output_size: 256
  backbone_name: ResNet50
  backbone_params:
    pretrained: true
  classify_params:
    num_classes: 2
  classifyr_name: BaseClassify
