python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name swin_b  --batch_size 1 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name swin_v2_s  --batch_size 1 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name vit_h_14   --batch_size 1 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name regnet_y_128gf   --batch_size 1 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name regnet_y_32gf    --batch_size 2 --strategy ddp --device 4

python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name convnext_base --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name convnext_large --batch_size 2 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name convnext_small --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name convnext_tiny --batch_size 4 --strategy ddp --device 4

python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name densenet161 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name densenet201 --batch_size 4 --strategy ddp --device 4

python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b0 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b1 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b2 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b3 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b4 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b5 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b6 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_b7 --batch_size 4 --strategy ddp --device 4

python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_v2_l --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_v2_m --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name efficientnet_v2_s --batch_size 4 --strategy ddp --device 4

python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name inception_v3 --batch_size 4 --strategy ddp --device 4
python3 train.py --train_path /home/lab/inseo/cancer/data/train_re.csv --test_path /home/lab/inseo/cancer/data/test_re.csv --weight_path /home/lab/inseo/cancer/ --log_path /home/lab/inseo/cancer/ --model_name resnet101  --batch_size 4 --strategy ddp --device 4
